[package]
name = "bolas"
version.workspace = true
edition.workspace = true
authors.workspace = true
build = "build.rs"

[dependencies]
actix = { workspace = true }
actix-files = { workspace = true }
actix-web = { workspace = true }
actix-web-actors = { workspace = true }
bio = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
libsystemd = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
vergen = { workspace = true }

[dev-dependencies]
rusty-hook = { workspace = true }
