[package]
name = "bolas"
version = "0.1.0"
edition = "2018"
authors = ["John Norwood"]

[dependencies]
actix = { workspace = true }
actix-files = { workspace = true }
actix-web = { workspace = true }
actix-web-actors = { workspace = true }
bio = { workspace = true }
env_logger = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
rusty-hook = { workspace = true }
