[package]
name = "bolas"
version.workspace = true
edition.workspace = true
authors.workspace = true
build = "build.rs"

[dependencies]
actix = { workspace = true }
actix-files = { workspace = true }
actix-http = { workspace = true }
actix-service = { workspace = true }
actix-web = { workspace = true }
actix-web-actors = { workspace = true }
bio = { workspace = true }
foundations = { workspace = true }
futures = { workspace = true }
libsystemd = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
vergen = { workspace = true }

[dev-dependencies]
rusty-hook = { workspace = true }
