[workspace]
members = [
    "bin/bolas",
]

[workspace.dependencies]
actix = "0.13"
actix-files = "0.6"
actix-web = "4.2"
actix-web-actors = "4.1"
env_logger = "0.10"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
